# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f32faeab6368369c7e906a547c4c3be20d45438da8fd597accacca9ab87650678ccd848bbcad468d863483a24d9ff152d5c3aabb951a9eaf6de2d3866aa6349

test:
  secret_key_base: 0785bdeeac2ee33f0614c6c8d722e3503e09a700b72c31b4817c3ba74929dd9733694f77505dc2d70122139a4ab38288639ab5d3831fc470f6deca1a06665ca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
